import { MessageCircle } from "lucide-react";
import type { Loja } from "@/lib/sanity-client";

export default function StoreCard({ store }: { store: Loja }) {
  const phone = store.whatsapp.replace(/\D/g, "");
  const mapAddress = encodeURIComponent(store.endereco);
  const mapEmbedUrl = `https://www.google.com/maps?q=${mapAddress}&output=embed`;

  return <article className="overflow-hidden rounded-3xl bg-white shadow-sm ring-1 ring-dourado/30"><div className="p-6 sm:p-7"><p className="text-sm font-bold uppercase tracking-[0.15em] text-vermelho">Unidade</p><h2 className="mt-2 font-titulo text-2xl font-bold text-marrom-escuro">Unidade {store.unidade}</h2><p className="mt-2 font-semibold text-marrom-escuro/80">{store.cidadeEstado}</p><address className="mt-5 not-italic text-sm leading-6 text-marrom-escuro/75"><strong className="text-marrom-escuro">Endereço:</strong> {store.endereco}{store.referencia && <><br /><strong className="text-marrom-escuro">Referência:</strong> {store.referencia}</>}</address><a href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-bold text-whatsapp"><MessageCircle size={17} /> {store.whatsapp}</a><div className="mt-5"><p className="text-sm font-bold text-marrom-escuro">Horário</p><div className="mt-1 text-sm leading-6 text-marrom-escuro/75">{store.horario.map((line) => <p key={line}>{line}</p>)}</div></div><p className="mt-5 rounded-2xl border-l-4 border-dourado bg-dourado/15 px-4 py-3 text-sm font-semibold leading-6 text-marrom-escuro">{store.avisoDestaque}</p><div className="mt-6 grid gap-3 sm:grid-cols-2"><a href={`https://wa.me/${phone}`} target="_blank" rel="noreferrer" className="inline-flex items-center justify-center gap-2 rounded-full bg-whatsapp px-4 py-3 text-center text-sm font-bold text-white hover:bg-whatsapp/90"><MessageCircle size={17} /> Chamar no WhatsApp</a><a href={store.googleMapsUrl} target="_blank" rel="noreferrer" className="rounded-full border-2 border-marrom-escuro px-4 py-3 text-center text-sm font-bold text-marrom-escuro hover:bg-creme">Ver rota no Google Maps</a></div></div><div className="relative h-[270px] overflow-hidden"><iframe title={`Mapa da ${store.unidade}`} src={mapEmbedUrl} className="h-full w-full border-0" loading="lazy" referrerPolicy="no-referrer-when-downgrade" /><a href={store.googleMapsUrl} target="_blank" rel="noreferrer" className="absolute bottom-3 right-3 rounded-full bg-white px-4 py-2 text-xs font-bold text-marrom-escuro shadow-md">Abrir no Maps</a></div></article>;
}
